import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "../components/Hero";
import Corevalues from "../components/Corevalues";
import Aboutus from "../components/Aboutus";
// import Testimonals from "../components/Testimonals";
import Calltoaction from "../components/Calltoaction";
import Bigfeature from "../components/Bigfeature";
import Learnmore from "@/components/Learnmore";
import Team from "@/components/Team";
import Otherfeature from "@/components/Otherfeature";
import Faq from "@/components/Faq";
import Locations from "@/components/Locations";
import Secondcta from "@/components/Secondcta";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Arise Autism Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero></Hero>
      <Corevalues></Corevalues>
      <Bigfeature> </Bigfeature>
      <Calltoaction></Calltoaction>
      <Learnmore></Learnmore>
      <Otherfeature></Otherfeature>
      <Team></Team>
      <Secondcta></Secondcta>
      <Faq></Faq>
      <Locations></Locations>
    </>
  );
}
